services:
  cloudsubbot:
    image: docker.cnb.cool/cloud115/cloudsubbot:1.0.5
    platform: linux/amd64
    container_name: cloudsubbot
    restart: unless-stopped
    ports:
      - "9114:9114"
    environment:
      - ENV=production
      - DB_PATH=/database/sqlite.db
    volumes:
      - ./database/sqlite.db:/database/sqlite.db
