services:
  cloudsubbot:
    image: docker.cnb.cool/cloud115/cloudsubbot:1.0.6
    platform: linux/amd64
    container_name: cloudsubbot
    restart: unless-stopped
    ports:
      - "9114:9114"
    environment:
      - ENV=production
      - DB_PATH=/database/sqlite.db
      - TZ=Asia/Shanghai
    volumes:
      - ./database:/database
